package main

func main() {
	// fmt.Println(sprint.Abacus(8, 3))
	// fmt.Println(sprint.Abacus(9, 2))
	// fmt.Println(sprint.Mean(1.15, -2.0, 8.35))
	// fmt.Println(sprint.Casting(1.15))
	// fmt.Println(sprint.ShiftBy('a', 4))
	// fmt.Printf("%c\n", sprint.ShiftBy('a', 4))
	// fmt.Println(sprint.StrConcat("r", "ProgrammerHumour", "/"))
	// fmt.Println(sprint.ReverseAlphabetValue('a'))
	// fmt.Println(sprint.IsNegative(1))
	// fmt.Print((sprint.IntVsFloat(5, 8.8)))
	// fmt.Println(sprint.IntVsFloat(-8, -8.8))
	// fmt.Println(sprint.Season("feb"))
	// fmt.Println(sprint.Season("September"))
	// fmt.Println(sprint.Accumulate(10))
	// fmt.Println(sprint.BetweenLimits('j', 'f'))
	// fmt.Println(sprint.Doop(5, "%", 3))
	// fmt.Println(sprint.Doop(8, "/", 0))
	// fmt.Println(sprint.IsLeapYear(2020))
	// fmt.Println(sprint.IsLeapYear(1900))
	// fmt.Println(sprint.CountDivisible(5, 17, 2, 3))
	// fmt.Println(sprint.FindDividend(5, 17, 4))
	// fmt.Println(sprint.FindDividend(10, 18, 9))
	// fmt.Println(sprint.AlphabetMastery(6))
	//fmt.Println(sprint.ReverseAlphabet(5))
	//fmt.Printf(sprint.Pairs())
	//fmt.Printf(sprint.Combinations())
	//fmt.Println(sprint.Countdown(5))
	//fmt.Println(sprint.AlphaNumber(1280))
	//fmt.Println(sprint.SimpleStrToInt("10203"))
	// fmt.Println(sprint.SimpleStrToInt("0000000010203"))
	//fmt.Println(sprint.StrToInt("--10203"))

}
